source 'https://rubygems.org'


gem 'rails', '4.1.6'

gem 'rails-api'

gem 'omniauth'
gem 'devise_token_auth'
gem 'bcrypt'

gem 'spring', :group => :development


gem 'sqlite3'

group 'test' do
    gem 'rspec'
    gem 'shoulda'
    gem 'factory_girl'
end


# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
